title:            Jeff Chen
description:      2006 TIME Magazine Person of the Year
url:              '' # Site url, without a slash at the end.
signoff:          Jeff Chen # Your name.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
github:           jchen1
twitter:          iambald
email:            hello@jeff.yt
linkedin:         jchen94

collections:
  - projects

links:
  - name:         Home
    url:          /
  - name:         Projects
    url:          /projects/
  - name:         Résumé
    url:          /resume/
highlighter:      rouge
permalink:        pretty
markdown:         kramdown

gems: [bourbon, neat]